cart/urls.py
from django.urls import path

from cart.views import AddToCartView, CartView, CheckoutAPIView, SuccessView

app_name = 'cart'

urlpatterns = [
    path('checkout/', CartView.as_view(), name='checkout'),
    # ... other URL patterns ...
    path('api/add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('api/checkout/', CheckoutAPIView.as_view(), name='api-checkout'),
    path('success/', SuccessView.as_view(), name='success'),
]

contact/urls.py
from django.urls import path

from contact.views import ContactView, newsletterSubscribe, sendMessage


app_name = 'contact'

urlpatterns = [
   path('', ContactView.as_view(), name='main-page'),
#    path('subscribe/', newsletterSubscribe, name='newsletter'),
#    path('sendmessage/', sendMessage, name='send-message')
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='homepage'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('terms-privacy/', views.TermsAndPrivacyView.as_view(), name='terms-privacy'),
    path('services/micro-loans/', views.MicroLoanView.as_view(), name='micro-loans'),
    path('services/paint/', views.PaintView.as_view(), name='paint'),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsView.as_view(), name='list'),
    path('<int:pk>/', views.PostView.as_view(), name='detail'),
]

products/urls.py
from products.views import CategoryListView, ProductCreateView, ProductDeleteView, ProductDetailView, ProductListView, ProductUpdateView
from django.urls import path


app_name = 'products'

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('categories/<int:pk>/', ProductListView.as_view(), name='products-by-category'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    
    path('', ProductListView.as_view(), name='all-products'),
    path('create/', ProductCreateView.as_view(), name='product-create'),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
]

superapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from accounts.admin import user_admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('u-admin/', user_admin.urls),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('consultancy/', include('consultancy.urls', namespace='consultancy')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('vehicles/', include('vehicles.urls', namespace='vehicles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls', namespace='main')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_components/footer.html
{% load static %}

<footer class="w-full text-gray-700 bg-light body-font pt-20 sm:pt-24">
    <div class="container px-5 mx-auto grid sm:grid-cols-2 lg:grid-cols-4 gap-2 justify-center content-center">
        <!-- logo -->
        <div class="flex-shrink-0 w-64 text-center md:mx-0 md:text-left mb-20 sm:col-span-2 xl:col-span-1 grid justify-center">
            <a class="flex items-center justify-center font-medium text-gray-900 title-font md:justify-start">
                <img src="{% static 'images/logo-trans.png' %}" alt="" class="w-48">
            </a>
            <div class="mt-4 grid justify-center">
                <span class="inline-flex justify-center mt-2 sm:ml-auto sm:mt-0">
                    <a class="text-gray-500 cursor-pointer hover:text-gray-700">
                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            class="w-5 h-5" viewBox="0 0 24 24">
                            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                        </svg>
                    </a>
                    <a class="ml-3 text-gray-500 cursor-pointer hover:text-gray-700">
                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            class="w-5 h-5" viewBox="0 0 24 24">
                            <path
                                d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z">
                            </path>
                        </svg>
                    </a>
                    <a class="ml-3 text-gray-500 cursor-pointer hover:text-gray-700">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                        </svg>
                    </a>
                    <a class="ml-3 text-gray-500 cursor-pointer hover:text-gray-700">
                        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round"
                            stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
                            <path stroke="none"
                                d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z">
                            </path>
                            <circle cx="4" cy="4" r="2" stroke="none"></circle>
                        </svg>
                    </a>
                </span>
            </div>
        </div>
        <!-- about -->
        <div class="w-full px-4">
            <h2 class="mb-3 text-sm font-medium tracking-widest text-secondary uppercase title-font">About</h2>
            <nav class="mb-10 list-none">
                <li class="mt-3">
                    <a href="{% url 'main:about' %}" class="text-gray-500 cursor-pointer hover:text-secondary">Company</a>
                </li>
                <li class="mt-3">
                    <a href="{% url 'posts:list' %}" class="text-gray-500 cursor-pointer hover:text-secondary">Posts</a>
                </li>
                <li class="mt-3">
                    <a href="{% url 'main:terms-privacy' %}" class="text-gray-500 cursor-pointer hover:text-secondary">Terms &amp; Privacy</a>
                </li>
            </nav>
        </div>
        <!-- support -->
        <div class="w-full px-4">
            <h2 class="mb-3 text-sm font-medium tracking-widest text-secondary uppercase title-font">Services</h2>
            <nav class="mb-10 list-none">
                <li class="mt-3">
                    <a href="{% url 'consultancy:consultancy' %}" class="text-gray-500 cursor-pointer hover:text-secondary">Consultancy</a>
                </li>
                <li class="mt-3">
                    <a href="{% url 'vehicles:list' %}" class="text-gray-500 cursor-pointer hover:text-secondary">Vehicles</a>
                </li>
                <li class="mt-3">
                    <a href="{% url 'products:categories' %}" class="text-gray-500 cursor-pointer hover:text-secondary">Farm Produce</a>
                </li>
            </nav>
        </div>
        <!-- contact -->
        <div class="w-full px-4">
            <h2 class="mb-3 text-sm font-medium tracking-widest text-secondary uppercase title-font">Contact</h2>
            <nav class="mb-10 list-none">
                <li class="mt-3">
                    <a href="{% url 'contact:main-page' %}" class="text-gray-500 cursor-pointer hover:text-secondary">Send a Message</a>
                </li>
                <li class="mt-3">
                    <a class="text-gray-500 cursor-pointer hover:text-secondary">info@sil-pi.com</a>
                </li>
                <li class="mt-3">
                    <a href="tel:+256772601644" class="text-gray-500 cursor-pointer hover:text-secondary">+256-772-601644</a>
                </li>
            </nav>
        </div>
    </div>
    <div class="">
        <div class="container px-5 py-4 mx-auto">
            <p class="text-sm text-muted capitalize text-center">Powered by DakDot © <span id="yearFooter"></span></p>
        </div>
        
        <script>
            document.getElementById('yearFooter').textContent = new Date().getFullYear();
        </script>
        
    </div>
</footer>

templates/base_components/header.html
{% load static %}

<!-- Navbar -->

<div x-data='{ 
    menu: false,
    services_menu: true
}'>
    <nav class="nav py-3 w-full fixed top-0 left-0 right-0 z-[9001]">

        <div class="container px-3 mx-auto flex justify-between items-center">
            <!-- Logo Container -->
            <div class="flex items-center">
                <!-- Logo -->
                <a class="bg-white py-4 px-2 rounded-lg shadow-sm" href="/">
                    <img src="{% static 'images/logo-trans.png' %}" alt="" class="w-20 sm:w-28">
                </a>
            </div>

            <!-- Links Section -->
            <div class="items-center hidden space-x-8 md:flex bg-white px-6 py-2 rounded-full shadow-sm">
                <a href="/" class="flex hover:text-primary-500
                    cursor-pointer transition-colors duration-300">
                    Home
                </a>

                <div
                    class="flex cursor-pointer transition-colors duration-300 relative items-center gap-3 group min-w-fit">
                    Services <i class="fas fa-angle-down"></i>
                    <div
                        class="dropdown absolute top-8 -left-[11rem] pointer-events-auto p-6 rounded-xl bg-white min-w-[30rem]">
                        <div class="grid grid-cols-2 gap-y-4 text-primary-800">
                            <div class="grid gap-y-3 content-start">
                                <h3 class="font-bold text-sm text-grey-400">Services</h3>
                                <hr>
                                <!-- <a href="{% url 'consultancy:portfolio' %}"
                                    class="flex cursor-pointer transition-colors duration-300 hover:text-primary-600">
                                    View Portfolio
                                </a> -->
                                <a href="{% url 'consultancy:consultancy' %}"
                                    class="flex cursor-pointer transition-colors duration-300 hover:text-primary-600">
                                    Consultancy
                                </a>
                                <a href="{% url 'main:micro-loans' %}" class="flex 
                                cursor-pointer transition-colors duration-300
                            hover:text-primary-600">
                                    Micro Lending
                                </a>
                            </div>

                            <div class="grid gap-y-3 content-start">
                                <h3 class="font-bold text-sm text-grey-400">Products</h3>
                                <hr>
                                <a href="{% url 'main:paint' %}" class="flex 
                                cursor-pointer transition-colors duration-300
                            hover:text-primary-600">
                                    Paint
                                </a>
                                <a href="{% url 'vehicles:list' %}" class="flex 
                                cursor-pointer transition-colors duration-300
                            hover:text-primary-600">
                                    Get a car
                                </a>
                                <a href="{% url 'products:categories' %}" class="flex 
                                cursor-pointer transition-colors duration-300
                            hover:text-primary-600">
                                    Order Farm Products
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <a href="{% url 'main:about' %}" class="flex hover:text-primary-500
                    cursor-pointer transition-colors duration-300">
                    About Us
                </a>

            </div>

            <a href="{% url 'contact:main-page' %}" class="hidden sm:flex shadow-sm">
                <c-ui.button text="Contact Us" icon="fas fa-phone" variant="white" />
            </a>

            <!-- Icon Menu Section -->
            <div class="md:hidden" @click="menu=!menu">
                <c-ui.button variant="white" size="iconXl" title="Nav toggle">
                    <i class="fas text-lg" :class="menu ? 'fa-close' : 'fa-bars'"></i>
                </c-ui.button>
            </div>
        </div>

    </nav>

    <menu x-cloak x-show="menu" x-transition
        class="fixed top-0 left-0 bottom-0 right-0 h-[100dvh] bg-white lg:hidden z-[9000]">
        <div class="grid content-start gap-6 mt-36 px-4 text-secondary">
            <a href="/" class="">
                Home
            </a>

            <a href="{% url 'main:about' %}">
                About Us
            </a>

            <div class=" grid gap-4 rounded-lg">
                <button @click="services_menu = !services_menu"
                    class="text-primary-800 text-left flex gap-8 items-center">Services <i class="fas"
                        :class="services_menu ? 'fa-angle-up' : 'fa-angle-down'"></i></button>
                <div class="grid gap-4 pl-4 border-l" x-cloak x-transition x-show="services_menu">
                    <!-- consultancy -->
                    <div class="grid gap-2">
                        <a href="{% url 'consultancy:consultancy' %}">
                            Consultancy
                        </a>
                    </div>
                    <!-- micro lending -->
                    <div class="grid gap-2 ">
                        <a href="{% url 'main:micro-loans' %}">
                            Micro Lending
                        </a>
                    </div>
                    <!-- vehicles -->
                    <div class="grid gap-2 ">
                        <a href="{% url 'vehicles:list' %}">
                            Get a vehicle
                        </a>
                    </div>
                    <!-- farming -->
                    <div class="grid gap-2 ">
                        <a href="{% url 'products:categories' %}">
                            Order Farm products
                        </a>
                    </div>
                </div>

            </div>

            <a href="{% url 'contact:main-page' %}" class="mt-8">
                <c-ui.button text="Let's Talk'" icon="fas fa-phone" />
            </a>

            <a href="tel:+256772601644">
                <i class="fas fa-phone mr-4 text-primary-900 text-xl"></i>
                +256 772 601644
            </a>

            <a href="mailto:silpi@gmail.com">
                <i class="fas fa-envelope mr-4 text-primary-900 text-xl"></i>
                silpi@gmail.com
            </a>
        </div>
    </menu>
</div>

<style>
    nav.nav {
        transition: all 0.3s ease-in-out;
    }

    nav.nav.hide {
        top: -200px;
    }

    nav.nav .group .dropdown {
        clip-path: circle(0% at 50% 0);
        transition: clip-path 0.5s ease-in-out;
    }

    nav.nav .group:hover .dropdown {
        clip-path: circle(70.7% at 50% 50%);
    }
</style>