cart/urls.py
from django.urls import path

from cart.views import AddToCartView, CartView, CheckoutAPIView, SuccessView

app_name = 'cart'

urlpatterns = [
    path('checkout/', CartView.as_view(), name='checkout'),
    # ... other URL patterns ...
    path('api/add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('api/checkout/', CheckoutAPIView.as_view(), name='api-checkout'),
    path('success/', SuccessView.as_view(), name='success'),
]

products/urls.py
from products.views import CategoryListView, ProductCreateView, ProductDeleteView, ProductDetailView, ProductListView, ProductUpdateView
from django.urls import path


app_name = 'products'

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('categories/<int:pk>/', ProductListView.as_view(), name='products-by-category'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    
    path('', ProductListView.as_view(), name='all-products'),
    path('create/', ProductCreateView.as_view(), name='product-create'),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
]

superapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from accounts.admin import user_admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('u-admin/', user_admin.urls),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('consultancy/', include('consultancy.urls', namespace='consultancy')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('vehicles/', include('vehicles.urls', namespace='vehicles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls', namespace='main')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'
        
    thumbnail = models.ImageField()
    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50)
    thumbnail = models.ImageField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    details = RichTextField()
    price = models.IntegerField(blank=True, null=True)
    available = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name
    

products/forms.py
from django import forms

from products.models import Product


class ProductModelForm(forms.ModelForm):
    """Form definition for Product."""

    class Meta:
        """Meta definition for Productform."""

        model = Product
        fields = '__all__'

products/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from contact.models import Receipient
from products.forms import ProductModelForm

from products.models import Category, Product


# Create your views here.
class CategoryListView(ListView):
    template_name = 'products/landing.html'
    queryset = Category.objects.all()
    context_object_name = 'categories'


class ProductListView(View):
    def get(self, request, pk=None):
        template_name = 'products/product_list.html'
        
        if pk:
            category = Category.objects.get(pk=pk)
            products = category.products.filter(available=True)
        else:
            category = 'All Products'
            products = Product.objects.filter(available=True)
        context = {
            'category': category,
            'products': products,
        }
        return render(request, template_name, context)


class ProductDetailView(View):
    def get(self, request, pk):
        template_name = 'products/product_detail.html'
        
        product = Product.objects.get(pk=pk)
        context = {
            'product': product,
        }
        return render(request, template_name, context)
    
    def post(self, request, pk):
        class Order():
            def __init__(self,product,name,email,phone) -> None:
                self.product = product
                self.name = name
                self.email = email
                self.phone = phone
                
        product = Product.objects.get(pk=pk)
        data = request.POST
        order = Order(product,data.get('name'),data.get('email'),data.get('phone'))
        
        # TODO send emails
        # Send email to TO_EMAILS
        to_emails_message = render_to_string('products/order-notification.html', {'order':order})
        send_mail(
            'Product Quotation Request',
            '',
            settings.DEFAULT_FROM_EMAIL,  # Replace with your email
            [r.email for r in Receipient.objects.all()],  # Replace with your recipient emails
            html_message=to_emails_message,
        )

        # Render the user email template
        user_message = render_to_string('vehicles/order-confirmation-user.html', {'email':data.get('email')})

        # Send confirmation email to the user
        send_mail(
            'Quotation Confirmation',
            '',
            settings.DEFAULT_FROM_EMAIL,  # Replace with your email
            [order.email],
            html_message=user_message,
            fail_silently=False,
        )
        return self.get(request, pk=pk)


class ProductCreateView(LoginRequiredMixin, CreateView):
    template_name = 'products/product_create.html'
    form_class = ProductModelForm


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'products/product_update.html'
    queryset = Product.objects.all()
    form_class = ProductModelForm

    def get_success_url(self):
        return reverse('products:productspage')


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'products/product_delete.html'
    queryset = Product.objects.all()
    form_class = ProductModelForm

    def get_success_url(self):
        return reverse('products:productspage')

products/templates/products/landing.html
{% extends 'base.html' %} {% load static %}


{% block content %}
<section class="banner relative min-h-[100dvh] bg-cover bg-no-repeat bg-center"
    style="background-image: url('{% static 'images/vegies.webp' %}');">
    <div class="absolute inset-0 grid items-center bg-gradient-to-br from-secondary/10 via-dark/80 to-secondary/40">
        <div class="container mx-auto text-center grid justify-center px-3">
            <h1 class="text-5xl md:text-7xl lg:text-8xl xl:text-9xl font-black text-white">Farm <br>Products</h1>
            <p class="text-xl text-light mb-8 max-w-2xl mx-auto">We offer a wide range of high-quality agricultural products, including fresh fruits, vegetables, pork, beef, and honey. Trust us for the best in farm-fresh produce and meats. Experience nature's bounty with our extensive selection.</p>
            <a href="#categories" class="mx-auto">
                <c-ui.button variant="white" text="Browse Products" icon="fas fa-arrow-down"/>
            </a>
        </div>
    </div>
</section>
<!-- categories -->
<section class="py-20" id="categories">
    <div class="container mx-auto">
        <h2 class="head__2">Select a category</h2>
        <div class="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
            {% for category in categories %}
            <a href="{% url 'products:products-by-category' category.pk %}">
                <article class="p-4 outline outline-1 transition-all group hover:shadow-lg hover:-rotate-3">
                    <div class="group-hover:rotate-3 transition-all ">
                        <img src="{{ category.thumbnail.url }}" alt="{{ category.name }} image" class="object-cover w-full aspect-[4/3] rounded-md">
                        <div class="mt-2">
                            <p class="text-primary-600 font-medium">{{ category.name }}</p>
                        </div>
                    </div>
                </article>
            </a>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

products/templates/products/order-notification.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SIL PI</title>
    <style>
        * {
            padding: 0;
            margin: 0;
            font-family: Poppins, 'sans-serif';
        }
    </style>
</head>

<body>
    <main style="background-color:rgb(4, 94, 94);color:white;">
        <header style="padding: 1rem;background-color:rgb(5, 139, 139);text-align: center;">
            <h1>
                <svg style="height: 1.5rem; margin-right:auto;margin-left:auto;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 629.33 152.36"><defs><style>.cls-1{fill:#00afaf;}</style></defs><title>COLORED SILPI</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M0,137.38l15.82-35.8c13.74,8.12,32.05,13.32,48.08,13.32,13.95,0,18.94-2.91,18.94-7.91,0-18.32-80.55-3.54-80.55-57.86C2.29,22.06,25,0,70.14,0c19.57,0,39.76,4.16,55,12.7L110.32,48.29C96,41,82.43,37.47,69.73,37.47c-14.36,0-18.94,4.16-18.94,9.16,0,17.48,80.55,2.91,80.55,56.62,0,26.64-22.69,49.12-67.86,49.12C39.13,152.36,14.57,146.33,0,137.38Z"/><path class="cls-1" d="M153.9,3.33H203V149H153.9Z"/><path class="cls-1" d="M224.95,3.33h49.12V110.94h65.77V149H224.95Z"/><path class="cls-1" d="M566.75,58.28c0,33.72-25.81,55-66.4,55h-21V149H430.21V3.33h70.15C540.94,3.33,566.75,24.56,566.75,58.28Zm-49.54,0c0-10.62-6.45-17.07-20-17.07h-17.9V75.35h17.9C510.76,75.35,517.22,68.9,517.22,58.28Z"/><path class="cls-1" d="M580.21,3.33h49.12V149H580.21Z"/></g></g></svg>
            </h1>
        </header>
        <div
            style="padding: 1rem;background-color:rgb(0, 54, 54);margin-top: .1rem;display: grid;row-gap: .5rem;text-align: center;color: rgb(200, 251, 251);">
            <h2 style="font-weight: 800;font-size: 1.2rem;">Product Quotation Request Details:</h2>
            <div>
                <p>Product: {{ order.product.name }}</p>
                <p>Details: {{ order.product.details }}</p>
            </div>
            <div>
                <p>Client Name: {{ order.name }}</p>
                <p>Client Email: {{ order.email }}</p>
                <p>Client Phone: {{ order.phone }}</p>
            </div>
        </div>
        <footer style="padding: 1rem;">
            <p style="text-align: center;">
                This email is as a result of a quotation request on sil-pi.com
            </p>
        </footer>
    </main>
</body>

</html>

products/templates/products/product_detail.html
{% extends 'base.html' %} {% load static %}

{% block content %}
<main class="pb-20 pt-20" x-data="$store.cart">

    <div class="container mx-auto">
        <div class="grid gap-8">
            <div class="grid md:grid-cols-2 gap-4">
                <img src="{{ product.thumbnail.url }}" alt="{{ product.name }}">
                <div>
                    <h3 class="font-semibold mt-2 mb-3 text-xl text-primary-700"><span>{{ product.name }}</span>. 
                        <span>{{ vehicle.model }}</span>
                    </h3>
                    <p>
                        {% if product.price %}
                        <span class="font-semibold mr-2">Price per unit:</span>
                        <span>{{ product.price }}</span>
                        {% else %}
                        <span>Price is variable, get a quote below for the current price.</span>
                        {% endif %}
                    </p>
                    <!-- <h4 class="font-semibold mt-2">More Details:</h4> -->
                    <p>{{ product.details|safe }}</p>
                </div>
            </div>
            <div>
                <form class="flex flex-wrap items-end justify-center gap-8 w-fit" method="post">
                    {% csrf_token %}
                    <div class="grid items-start gap-2">
                        <label for="name" class="font-semibold">Name *</label>
                        <input type="text" name="name" class="px-4 py-2 rounded-md outline outline-1 outline-gray-400"
                            required>
                    </div>
                    <div class="grid items-start gap-2">
                        <label for="email" class="font-semibold">Email *</label>
                        <input type="email" name="email" class="px-4 py-2 rounded-md outline outline-1 outline-gray-400"
                            required>
                    </div>
                    <div class="grid items-start gap-2">
                        <label for="phone" class="font-semibold">Phone *</label>
                        <input type="tel" name="phone" class="px-4 py-2 rounded-md outline outline-1 outline-gray-400"
                            required>
                    </div>
                    <button type="submit" class="px-6 py-2 bg-primary-500 w-fit text-white font-semibold">
                        Request a Quote
                        <i class="fas fa-arrow-right-long ml-3"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

{% block scriptssdfghj %}
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.store('cart', {
            item_id: Number('{{ product.pk }}'),
            quantity: 1,
            csrf() {
                const field = document.getElementById('token')?.firstElementChild
                return field.value;
            },
            async addToCart() {

                const obj = { product_id: this.item_id, quantity: this.quantity }

                const response = await fetch("{% url 'cart:add-to-cart' %}", {
                    method: 'POST',
                    headers: {
                        Accept: 'application/json',
                        'Content-Type': 'application/json',
                        'X-CSRFToken': this.csrf(),
                    },
                    body: JSON.stringify(obj),
                })
                const data = await response.json()
                console.log(data)
                window.location.href = '/cart/checkout/'
            }
        });
    })

</script>
{% endblock %}

products/templates/products/product_list.html
{% extends 'base.html' %} {% load static %}


{% block content %}
<!-- products -->
<div class="products py-20 mt-40">
    <div class="container mx-auto">
        {% if products.count > 0 %}
        <div class="grid lg:grid-cols-3 gap-4">
            {% for product in products %}
            <a href="{% url 'products:product-detail' product.pk %}">
                <article class="p-2 outline outline-1 transition-all group hover:shadow-lg hover:rotate-3">
                    <div class="group-hover:-rotate-3 transition-all ">
                        <img src="{{ product.thumbnail.url }}" alt="{{ product.name }}"
                            class="aspect-video object-cover w-full">
                        <h3 class="text-primary-600 font-medium">{{ product.name }}</h3>
                        <!-- <p>{{ product.price }}</p> -->
                    </div>
                </article>
            </a>
            {% endfor %}
        </div>
        {% else %}
        <div class="p-16 grid place-content-center gap-y-8">
            <p class="text-2xl md:text-5xl text-center">
                No products found!
            </p>
            <a href="{% url 'products:categories' %}" class="mx-auto w-fit">
                <c-ui.button text="Browse other categories" icon="fas fa-arrow-left"/>
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}