cart/urls.py
from django.urls import path

from cart.views import AddToCartView, CartView, CheckoutAPIView, SuccessView

app_name = 'cart'

urlpatterns = [
    path('checkout/', CartView.as_view(), name='checkout'),
    # ... other URL patterns ...
    path('api/add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('api/checkout/', CheckoutAPIView.as_view(), name='api-checkout'),
    path('success/', SuccessView.as_view(), name='success'),
]

consultancy/urls.py
from django.urls import path

from consultancy.views import ConsultancyListView, IndexView

app_name = 'consultancy'

urlpatterns = [
    path('', IndexView.as_view(), name='consultancy'),
    path('portfolio/', ConsultancyListView.as_view(), name='portfolio'),
]

services/urls.py
from services.views import ServiceCreateView, ServiceDeleteView, ServiceDetailView, ServiceListView, ServiceUpdateView
from django.urls import path

app_name = 'services'

urlpatterns = [
    path('', ServiceListView.as_view(), name='service-list'),
    path('create/', ServiceCreateView.as_view(), name='service-create'),
    path('<int:pk>/', ServiceDetailView.as_view(), name='service-detail'),
    path('<int:pk>/update/', ServiceUpdateView.as_view(), name='service-update'),
    path('<int:pk>/delete/', ServiceDeleteView.as_view(), name='service-delete'),
]

superapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from accounts.admin import user_admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('u-admin/', user_admin.urls),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('consultancy/', include('consultancy.urls', namespace='consultancy')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('vehicles/', include('vehicles.urls', namespace='vehicles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls', namespace='main')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

consultancy/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class ConsultancyProject(models.Model):
    title = models.CharField(max_length=200)
    description = RichTextField()
    client_name = models.CharField(max_length=100, null=True, blank=True)
    project_date = models.DateField()
    services_offered = models.CharField(max_length=200)
    project_duration = models.CharField(max_length=50)
    project_location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

services/forms.py
from services.models import Service
from django.forms import ModelForm


class ServiceModelForm(ModelForm):
    class Meta:
        model = Service
        fields = (
            'name',
            'description'
        )

consultancy/views.py
from django.shortcuts import render
from django.views import View

from consultancy.models import ConsultancyProject

# Create your views here.
class IndexView(View):
    def get(self, request):
        template_name = 'consultancy/consultancy.html'
        context = {}
        return render(request, template_name, context)


class ConsultancyListView(View):
    def get(self, request, *args, **kwargs):
        projects = ConsultancyProject.objects.all()
        template_name = 'consultancy/projects.html'
        context = {
            "projects": projects
        }
        return render(request, template_name, context)

services/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from services.forms import ServiceModelForm
from django.shortcuts import reverse, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Service

# Create your views here.
class ServiceListView(ListView):
    template_name = 'services/service_list.html'
    queryset = Service.objects.all()
    context_object_name = 'services'


class ServiceDetailView(DetailView):
    template_name = 'services/service_detail.html'
    queryset = Service.objects.all()
    context_object_name = 'service'


class ServiceCreateView(LoginRequiredMixin, CreateView):
    template_name = 'services/service_create.html'
    queryset = Service.objects.all()
    form_class = ServiceModelForm

    def get_success_url(self):
        return reverse('services:servicespage')


class ServiceUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'services/service_update.html'
    queryset = Service.objects.all()
    form_class = ServiceModelForm

    def get_success_url(self):
        return reverse('services:servicespage')


class ServiceDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'services/service_delete.html'
    queryset = Service.objects.all()
    form_class = ServiceModelForm

    def get_success_url(self):
        return reverse('services:servicespage')

services/templates/services/consultancy.html
{% extends 'base.html' %} {% load static %}


{% block content %}
<!-- categories -->
<section class="py-20 pt-40">
    <div class="container mx-auto">
        
    </div>
</section>

{% endblock content %}

services/templates/services/service_list.html
{% extends 'base.html' %} {% load crispy_forms_filters, static %}

{% block content %}
<!-- services -->
<div class="services">
    <div class="container">
        <h1 class="display-4 text-center text-uppercase">
            our services
        </h1>
    </div>
    <div class="container">
        {% if request.user.is_authenticated %}
        <a href="{% url 'services:service-create' %}" class="h4 text-primary text-decoration-none d-flex justify-content-end w-100">Add a service</a>
        {% endif %}
        <div class="row justify-content-between">
            {% for service in services %}
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="text-start py-5 px-3 w-90 my-3">
                    <h4 class="fw-bold"><a class="text-decoration-none" href="{% url 'services:service-detail' service.pk %}">{{ service.name }}</a></h4>
                    <p class="">
                        {{ service.description }}
                    </p>
                </div>
            </div>
           {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}